---
abstract: 'data selection dsl parser and applicator'
author:
  - 'Justin DeVuyst, C<justin@devuyst.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Selector
name: Data-Selector
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: '1.01'
